#!/bin/bash
# Testnia one-shot VPS setup + deploy script.
#
# Run as root on the Hostinger VPS (Browser terminal or SSH):
#   bash <(curl -fsSL https://raw.githubusercontent.com/Testnia-HQ/testnia/main/deploy/setup-vps.sh)
#
# Requires:
#   - A GitHub deploy key installed at ~/.ssh (see docs/VPS_HANDOFF.md).
#   - Docker + compose plugin (installs automatically if missing).
#
# Secrets not supplied via env are auto-generated and printed at the end.
# Override with env vars:
#   PB_ENCRYPTION_KEY, PB_SUPERUSER_EMAIL, PB_SUPERUSER_PASSWORD,
#   PAYSTACK_SECRET_KEY, INTEGRATED_AI_API_URL, INTEGRATED_AI_API_KEY,
#   BUILDER_MAILER_API_URL, BUILDER_MAILER_API_KEY, BUILDER_MAILER_SENDER_ADDRESS

set -euo pipefail

REPO="git@github.com:Testnia-HQ/testnia.git"
BRANCH="main"
APP_DIR="/opt/testnia"
DOMAIN="${DOMAIN:-testnia.com}"

log()  { printf '\n\033[1;34m==>\033[0m %s\n' "$*"; }
warn() { printf '\033[1;33m[warn]\033[0m %s\n' "$*"; }

# --- 1. Root check ----------------------------------------------------------
if [ "$(id -u)" -ne 0 ]; then
  echo "Run as root (or with sudo)." >&2
  exit 1
fi

# --- 2. Docker install ------------------------------------------------------
log "Checking Docker..."
if ! command -v docker >/dev/null 2>&1; then
  log "Installing Docker..."
  curl -fsSL https://get.docker.com | sh
fi
if ! docker compose version >/dev/null 2>&1; then
  log "Installing compose plugin..."
  apt-get update -qq
  apt-get install -y -qq docker-compose-plugin || true
fi
systemctl enable --now docker >/dev/null 2>&1 || true

# --- 3. SSH agent check (deploy key) ----------------------------------------
log "Testing GitHub SSH access..."
mkdir -p ~/.ssh && chmod 700 ~/.ssh
if ! ssh -o StrictHostKeyChecking=accept-new -o BatchMode=yes -T git@github.com >/dev/null 2>&1; then
  echo "GitHub SSH auth failed. Ensure the VPS public key is added as a repo Deploy Key." >&2
  exit 1
fi

# --- 4. Clone / update repo -------------------------------------------------
log "Cloning ${REPO} (branch ${BRANCH})..."
if [ -d "$APP_DIR/.git" ]; then
  git -C "$APP_DIR" fetch origin
  git -C "$APP_DIR" checkout "$BRANCH"
  git -C "$APP_DIR" pull --ff-only origin "$BRANCH"
else
  git clone --branch "$BRANCH" "$REPO" "$APP_DIR"
fi
cd "$APP_DIR"

# --- 5. Environment file ----------------------------------------------------
ENV_FILE="$APP_DIR/.env"
if [ ! -f "$ENV_FILE" ]; then
  log "Creating .env from defaults..."
  : "${PB_ENCRYPTION_KEY:=$(openssl rand -base64 32)}"
  : "${PB_SUPERUSER_EMAIL:=admin@$DOMAIN}"
  : "${PB_SUPERUSER_PASSWORD:=$(openssl rand -base64 18 | tr -d '/+=')}"
  cat > "$ENV_FILE" <<EOF
# Auto-generated by setup-vps.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)
VITE_PB_URL=https://pb.${DOMAIN}
VITE_API_URL=https://api.${DOMAIN}
PB_APP_NAME=Testnia
PB_APP_URL=https://pb.${DOMAIN}
PB_PUBLIC_URL=https://pb.${DOMAIN}
PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY}
PB_SUPERUSER_EMAIL=${PB_SUPERUSER_EMAIL}
PB_SUPERUSER_PASSWORD=${PB_SUPERUSER_PASSWORD}
CORS_ORIGIN=https://${DOMAIN}
PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY:-}
WEBSITE_URL=https://${DOMAIN}
INTEGRATED_AI_API_URL=${INTEGRATED_AI_API_URL:-}
INTEGRATED_AI_API_KEY=${INTEGRATED_AI_API_KEY:-}
PROXY_ENTRANCE_ID=${PROXY_ENTRANCE_ID:-}
WEBSITE_ID=${WEBSITE_ID:-}
BUILDER_MAILER_API_URL=${BUILDER_MAILER_API_URL:-}
BUILDER_MAILER_API_KEY=${BUILDER_MAILER_API_KEY:-}
BUILDER_MAILER_SENDER_ADDRESS=${BUILDER_MAILER_SENDER_ADDRESS:-}
EOF
  chmod 600 "$ENV_FILE"
else
  warn "Using existing $ENV_FILE (values kept)."
fi

# --- 6. Build + start -------------------------------------------------------
log "docker compose up --build -d..."
docker compose --env-file "$ENV_FILE" up -d --build

# --- 7. Health checks -------------------------------------------------------
log "Waiting for services..."
for svc in pocketbase api web caddy; do
  for i in $(seq 1 30); do
    if [ "$(docker inspect -f '{{.State.Health.Status}}' "testnia-$svc-1" 2>/dev/null)" = "healthy" ]; then
      break
    fi
    sleep 2
  done
done

log "Container status:"
docker compose --env-file "$ENV_FILE" ps

log "Deploy complete."
echo
echo "Credentials (save these):"
echo "  PB_ENCRYPTION_KEY=${PB_ENCRYPTION_KEY}"
echo "  PB_SUPERUSER_EMAIL=${PB_SUPERUSER_EMAIL}"
echo "  PB_SUPERUSER_PASSWORD=${PB_SUPERUSER_PASSWORD}"
echo
echo "Sites:"
echo "  https://${DOMAIN}        (web / Caddy auto-TLS)"
echo "  https://pb.${DOMAIN}     (PocketBase admin)"
echo "  https://api.${DOMAIN}    (API /health)"
echo
warn "Point DNS A records for ${DOMAIN}, pb.${DOMAIN}, api.${DOMAIN} to this VPS IP before TLS can issue."